### ISSUE TITLE
Add default settings 

### ISSUE THREAD

**Issue by pauldendulk** [kevlatus/vscode-theme-switcher#2]
Hi! I am surprised there is still a discussion between dark versus light mode while the obvious solution is to switch depending on the light outside. https://twitter.com/migueldeicaza/status/1005124262099709952. I guess your plugin is the one thing they are still missing :)

One thing to make it slightly easier to use is to start of with default settings. One obvious pick would be the out of the box dark mode. My other pick would be blue because that is the default and I guess most developers still use this.

**Comment by kevlatus** [comment]
Thanks for the positive feedback and suggestion!

I just updated the extension (da2054a3ea186b876500761ff94bc7a7d95f1a2e) to use the default dark and light themes. Additionally, you can set your preferred themes in the VS Code settings
