### ISSUE TITLE
change theme on sunrise/sunset

### ISSUE THREAD

**Issue by kevlatus** [kevlatus/vscode-theme-switcher#3]
[Algorithm for sunset/sunrise calculation](https://www.esrl.noaa.gov/gmd/grad/solcalc/main.js)

**Comment by lavir** [comment]
> [Algorithm for sunset/sunrise calculation](https://www.esrl.noaa.gov/gmd/grad/solcalc/main.js)

This one can be a solution for you [Sundial](https://marketplace.visualstudio.com/items?itemName=muuvmuuv.vscode-sundial)

**Comment by kevlatus** [comment]
closing this to due to project archival
